### ISSUE TITLE
Cyphal/UDP transfer <-> address/port conversion

### ISSUE THREAD

**Issue by ASMfreaK** [OpenCyphal/specification#115]
For #98 the specification in [pycyphal](https://pycyphal.readthedocs.io/en/stable/api/pycyphal.transport.udp.html) does not specify conversion between transfer to address and port.

It would be great to integrate [this](https://github.com/OpenCyphal/pycyphal/blob/338e206b375c230b96411ca4d5249087273bce36/pycyphal/transport/udp/_ip/_endpoint_mapping.py#L172-L192) documentation with [this part](https://github.com/OpenCyphal/pycyphal/blob/338e206b375c230b96411ca4d5249087273bce36/pycyphal/transport/udp/_ip/_endpoint_mapping.py#L25-L36) in the first text part of the specification.

Maybe something like this:

| Transfer kind | Address | Port |
| --- | --- | --- |
| Message |  Multicast base + subnet id + subject id | `SUBJECT_PORT = 16383` |
| Service | Target address | `SERVICE_BASE_PORT = 16384;`<br/> `TARGET_PORT =  SERVICE_BASE_PORT + service_id * 2 + responce_not_request` |

**Comment by pavel-kirienko** [comment]
Superseded by https://github.com/OpenCyphal/specification/issues/98
