### ISSUE TITLE
Specify Cyphal/UDP

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/specification#98]
The draft is available at https://pycyphal.readthedocs.io/en/stable/api/pycyphal.transport.udp.html

The discussion is at https://forum.opencyphal.org/t/alternative-transport-protocols-in-uavcan/324

**Comment by ASMfreaK** [comment]
Please cyphalize the link: https://pycyphal.readthedocs.io/en/stable/api/pycyphal.transport.udp.html#cyphal-udp-transport-overview

**Comment by pavel-kirienko** [comment]
As discussed at the call, Cyphal/UDP will be available in v1.0 only as an experimental capability with the possibility of breaking changes in the future. The most recent draft is available on the forum here: https://forum.opencyphal.org/t/cyphal-udp-architectural-issues-caused-by-the-dependency-between-the-nodes-ip-address-and-its-identity/1765/60?u=pavel.kirienko
